name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Set up uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 #v7.1.2
      with:
        enable-cache: true
        cache-dependency-glob: "build_readme.py"

    - name: Update README
      run: |-
        uv run build_readme.py
        cat README.md

    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "readme-bot@haim.dev"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push
